version: '3.4'
x-common:
  &common
  image: erikap/ruby-sinatra
  volumes:
    - .:/usr/src/app
  networks:
    blebox_sensors:

services:
  airSensor:
    << : *common
    environment:
      MAIN_APP_FILE: products/airSensor.rb
      NAME: "My air 1"
  dimmerBox:
    << : *common
    environment:
      MAIN_APP_FILE: products/dimmerBox.rb
      NAME: "My dimmer 1"
  tempSensor:
    << : *common
    environment:
      MAIN_APP_FILE: products/tempSensor.rb
      NAME: "My temp 1"
  wLightBox:
    << : *common
    environment:
      MAIN_APP_FILE: products/wLightBox.rb
      NAME: "My light 1"
  saunaBox:
    << : *common
    environment:
      MAIN_APP_FILE: products/saunaBox.rb
      NAME: "My sauna 1"
  shutterBox:
    << : *common
    environment:
      MAIN_APP_FILE: products/shutterBox.rb
      NAME: "My shutter1"
  gateBox:
    << : *common
    environment:
      MAIN_APP_FILE: products/gateBox.rb
      NAME: "My gatebox 1"
  gateController:
    << : *common
    environment:
      MAIN_APP_FILE: products/gateController.rb
      NAME: "My gateController 1"
  wLightBoxS:
    << : *common
    environment:
      MAIN_APP_FILE: products/wLightBoxS.rb
      NAME: "My lightBoxS 1"
  switchBox:
    << : *common
    environment:
      MAIN_APP_FILE: products/switchBox.rb
      NAME: "My switchBox 1"
  switchBoxD:
    << : *common
    environment:
      MAIN_APP_FILE: products/switchBoxD.rb
      NAME: "My switchBoxD 1"

networks:
  blebox_sensors:
    external: true
