#!/bin/bash

set -o pipefail
set -eu

name="${1:-}"


if [ -z "$name" ]; then
  echo >&2 "No product name given. Showing all entries..."
  docker network inspect blebox_sensors | jq '.[0]["Containers"][] | (.IPv4Address + "  " + .Name)'
else
  docker network inspect blebox_sensors | jq ".[0][\"Containers\"][] | select(.Name | contains(\"$name\")) | .IPv4Address" | cut -d'"' -f2-|cut -d/ -f1
fi
